version: '3.8'

services:
  # Backend Node.js
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cinespark-backend
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=ClaveUltraSeguraCineSpark2024
    ports:
      - "4000:4000"
    networks:
      - cinespark-network
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend React
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cinespark-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cinespark-network

networks:
  cinespark-network:
    driver: bridge
